Fixed problem with configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -695,6 +695,8 @@ PKG_CONFIG
 GIMP_CFLAGS
 GIMP_LIBS
 GIMP_LIBDIR
+LQR_CFLAGS
+LQR_LIBS
 GETTEXT_PACKAGE
 USE_NLS
 INTLTOOL_UPDATE
@@ -737,8 +739,6 @@ PO_IN_DATADIR_FALSE
 POFILES
 POSUB
 MKINSTALLDIRS
-LQR_CFLAGS
-LQR_LIBS
 LQR_LIBDIR
 LOCALEDIR
 DATADIR
@@ -756,7 +756,9 @@ CPPFLAGS
 CPP
 PKG_CONFIG
 GIMP_CFLAGS
-GIMP_LIBS'
+GIMP_LIBS
+LQR_CFLAGS
+LQR_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1350,6 +1352,8 @@ Some influential environment variables:
   PKG_CONFIG  path to pkg-config utility
   GIMP_CFLAGS C compiler flags for GIMP, overriding pkg-config
   GIMP_LIBS   linker flags for GIMP, overriding pkg-config
+  LQR_CFLAGS  C compiler flags for LQR, overriding pkg-config
+  LQR_LIBS    linker flags for LQR, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -5229,6 +5233,119 @@ fi
 GIMP_LIBDIR=`$PKG_CONFIG --variable=gimplibdir gimp-2.0`
 
 
+LQR_REQUIRED_VERSION=0.5.0
+
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for LQR" >&5
+echo $ECHO_N "checking for LQR... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LQR_CFLAGS"; then
+        pkg_cv_LQR_CFLAGS="$LQR_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"lqr-1 >= \$LQR_REQUIRED_VERSION\"") >&5
+  ($PKG_CONFIG --exists --print-errors "lqr-1 >= $LQR_REQUIRED_VERSION") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LQR_CFLAGS=`$PKG_CONFIG --cflags "lqr-1 >= $LQR_REQUIRED_VERSION" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LQR_LIBS"; then
+        pkg_cv_LQR_LIBS="$LQR_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"lqr-1 >= \$LQR_REQUIRED_VERSION\"") >&5
+  ($PKG_CONFIG --exists --print-errors "lqr-1 >= $LQR_REQUIRED_VERSION") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LQR_LIBS=`$PKG_CONFIG --libs "lqr-1 >= $LQR_REQUIRED_VERSION" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LQR_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "lqr-1 >= $LQR_REQUIRED_VERSION"`
+        else
+	        LQR_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "lqr-1 >= $LQR_REQUIRED_VERSION"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LQR_PKG_ERRORS" >&5
+
+	{ { echo "$as_me:$LINENO: error: Package requirements (lqr-1 >= $LQR_REQUIRED_VERSION) were not met:
+
+$LQR_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LQR_CFLAGS
+and LQR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (lqr-1 >= $LQR_REQUIRED_VERSION) were not met:
+
+$LQR_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LQR_CFLAGS
+and LQR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LQR_CFLAGS
+and LQR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LQR_CFLAGS
+and LQR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	LQR_CFLAGS=$pkg_cv_LQR_CFLAGS
+	LQR_LIBS=$pkg_cv_LQR_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	:
+fi
 
 
 GETTEXT_PACKAGE=gimp20-plugin-template
@@ -8318,6 +8435,8 @@ PKG_CONFIG!$PKG_CONFIG$ac_delim
 GIMP_CFLAGS!$GIMP_CFLAGS$ac_delim
 GIMP_LIBS!$GIMP_LIBS$ac_delim
 GIMP_LIBDIR!$GIMP_LIBDIR$ac_delim
+LQR_CFLAGS!$LQR_CFLAGS$ac_delim
+LQR_LIBS!$LQR_LIBS$ac_delim
 GETTEXT_PACKAGE!$GETTEXT_PACKAGE$ac_delim
 USE_NLS!$USE_NLS$ac_delim
 INTLTOOL_UPDATE!$INTLTOOL_UPDATE$ac_delim
@@ -8331,8 +8450,6 @@ INTLTOOL_OAF_RULE!$INTLTOOL_OAF_RULE$ac_delim
 INTLTOOL_PONG_RULE!$INTLTOOL_PONG_RULE$ac_delim
 INTLTOOL_SERVER_RULE!$INTLTOOL_SERVER_RULE$ac_delim
 INTLTOOL_SHEET_RULE!$INTLTOOL_SHEET_RULE$ac_delim
-INTLTOOL_SOUNDLIST_RULE!$INTLTOOL_SOUNDLIST_RULE$ac_delim
-INTLTOOL_UI_RULE!$INTLTOOL_UI_RULE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -8374,6 +8491,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+INTLTOOL_SOUNDLIST_RULE!$INTLTOOL_SOUNDLIST_RULE$ac_delim
+INTLTOOL_UI_RULE!$INTLTOOL_UI_RULE$ac_delim
 INTLTOOL_XAM_RULE!$INTLTOOL_XAM_RULE$ac_delim
 INTLTOOL_KBD_RULE!$INTLTOOL_KBD_RULE$ac_delim
 INTLTOOL_XML_RULE!$INTLTOOL_XML_RULE$ac_delim
@@ -8401,8 +8520,6 @@ PO_IN_DATADIR_FALSE!$PO_IN_DATADIR_FALSE$ac_delim
 POFILES!$POFILES$ac_delim
 POSUB!$POSUB$ac_delim
 MKINSTALLDIRS!$MKINSTALLDIRS$ac_delim
-LQR_CFLAGS!$LQR_CFLAGS$ac_delim
-LQR_LIBS!$LQR_LIBS$ac_delim
 LQR_LIBDIR!$LQR_LIBDIR$ac_delim
 LOCALEDIR!$LOCALEDIR$ac_delim
 DATADIR!$DATADIR$ac_delim
